### ISSUE TITLE
Node.js 8.x is required

### ISSUE THREAD

**Issue by 190n** [particle-iot/wiring-preprocessor#10]
The version published on npm (`2.0.2`) requires Node.js 8.x. This makes it impossible to install `particle-cli` on my machine as I have Node.js 13.7.0. I see that the `package.json` in this repository has fixed that error; however, that version is not published on npm. When will that version be submitted to npm?

**Comment by busticated** [comment]
>This makes it impossible to install particle-cli on my machine as I have Node.js 13.7.0.

only if you aren't using `npm`. if, for example, you are using `yarn` instead, you can use the `--ignore-engines` flag ([docs](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines))

>When will that version be submitted to npm?

no specific ETA but likely in the near future

_closing this out as i think i answered your question. if not, feel free to re-open_:+1:

**Comment by 190n** [comment]
Thanks for the quick reply! I was in fact using `yarn` but didn't know about `--ignore-engines`. I'll use that in the meantime.
